apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
  namespace: default
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector: {}
  endpoints:
    - scheme: http
      port: http-metrics
      interval: "30s"
      path: /metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      follow_redirects: true
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-state-metrics
      app.kubernetes.io/name: kube-state-metrics
