apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
  namespace: default
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector: {}
  endpoints:
    - scheme: http
      port: http-metrics
      honorLabels: true
      metricRelabelConfigs:
        - source_labels:
          - namespace
          - pod
          target_label: node_name
          regex: (.+);(.+)
          replacement: $1-$2
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
