---
# Almost all linters; some of them are optional.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # The next six packages was removed in favour to github.com/percona-platform/dbaas-controller/k8s_api/... https://jira.percona.com/browse/PMM-6863
      - k8s.io/api/core/v1
      - k8s.io/apimachinery/pkg/api/resource
      - k8s.io/apimachinery/pkg/apis/meta/v1
      - k8s.io/apimachinery/pkg/apis/runtime
      - k8s.io/apimachinery/pkg/apis/types
      - k8s.io/apimachinery/pkg/apis/util/intstr

  goimports:
    local-prefixes: github.com/percona-platform/dbaas-controller

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - goerr113          # we use pkg/errors for stack traces
    - gomnd             # too annoying
    - lll               # gRPC types are long
    - wsl               # too annoying
    - unused            # too many false positives
    - nlreturn          # too annoying
    - exhaustivestruct  # too annoying
    - wrapcheck         # we don't wrap errors

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
        - unused       # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
