---
# Almost all linters; some of them are optional.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto

  goimports:
    local-prefixes: github.com/percona-platform/dbaas-controller

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - goerr113  # we use pkg/errors for stack traces
    - gomnd     # too annoying
    - lll       # gRPC types are long
    - wsl       # too annoying

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
        - unused       # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
