---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # Use service/k8sclient/internal/... instead
      - k8s.io/api/core/v1
      - k8s.io/apimachinery/pkg/api/resource
      - k8s.io/apimachinery/pkg/apis/meta/v1
      - k8s.io/apimachinery/pkg/apis/runtime
      - k8s.io/apimachinery/pkg/apis/types
      - k8s.io/apimachinery/pkg/apis/util/intstr
      - github.com/percona/percona-server-mongodb-operator
      - github.com/percona/percona-xtradb-cluster-operator

  goimports:
    local-prefixes: github.com/percona-platform/dbaas-controller

  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona-platform/dbaas-controller) # Groups all local imports.

linters:
  disable-all: true
  enable:
    # keep sorted
    - depguard
    - gci
    - goimports
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude-use-default: false
