apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: pmm-vm-cadvisor-metrics
spec:
  scheme: "https"
  interval: "10s"
  scrapeTimeout: "2s"
  selector: {}
  tlsConfig:
    insecureSkipVerify: true
    caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      # add value of namespace label to the another label
    - target_label: node_name
      source_labels: [namespace, pod]
      regex: '(.+);(.+)'
      replacement: $1-$2
