apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: pmm-vm-pod-scrape
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      relabelConfigs:
        - targetLabel: my_label_name
          sourceLabels: [namespace]
        - targetLabel: node_name
          sourceLabels: [namespace, pod]
          regex: '(.+);(.+)'
          replacement: $1-$2
  selector:
    matchLabels:
      monitored-by: vm-operator
