apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: pmm-vm-pod-scrape
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      relabelConfigs:
        - target_label: node_name
          source_labels: [namespace, pod]
          regex: '(.+);(.+)'
          replacement: $1-$2
          relabel_debug: true
  selector:
    matchLabels:
      monitored-by: vm-operator
