apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: pmm-vm-pod-scrape
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
  selector:
    matchLabels:
      monitored-by: vm-operator
  relabelConfigs:
      # add value of namespace label to the another label
    - target_label: node_name
      source_labels: [namespace, pod]
      regex: '(.+);(.+)'
      replacement: $1-$2
