apiVersion: v1
kind: Namespace
metadata:
  name: my-percona-xtradb-cluster-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-percona-xtradb-cluster-operator
spec:
  targetNamespaces:
  - my-percona-xtradb-cluster-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-percona-xtradb-cluster-operator
  namespace: my-percona-xtradb-cluster-operator
spec:
  channel: stable
  name: percona-xtradb-cluster-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
