apiVersion: v1
kind: Pod
metadata:
  name: hello1
spec:
  containers:
  - name: sleep10-1
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 10m
         memory: 32M
  - name: sleep10-2
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 0.01
         memory: 32Mi
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: hello2
spec:
  containers:
  - name: sleep10-1
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 10m
         memory: 0.1Gi
  - name: sleep10-2
    image: alpine
    command: ['sh', '-c', 'sleep 10 && exit 1']
    resources:
      requests:
         cpu: 10m
         memory: 20000000
  - name: sleep10-3
    image: alpine
    command: ['sh', '-c', 'sleep 10']
  initContainers:
  - name: sleep1-init
    image: alpine
    command: ['sh', '-c', 'sleep 1']
    resources:
      requests:
         cpu: 10m
         memory: 0.02Gi
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: hello3
spec:
  containers:
  - name: sleep10-1
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 600
         memory: 800Gi
  restartPolicy: Never
