apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-operator
  namespace: monitoring-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: vm-operator
  name: vm-operator
  namespace: monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: vm-operator
  template:
    metadata:
      labels:
        control-plane: vm-operator
    spec:
      containers:
        - args:
            - --enable-leader-election
          command:
            - manager
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: vm-operator
          image: victoriametrics/operator:v0.16.0
          name: manager
          resources:
            limits:
              cpu: 120m
              memory: 320Mi
            requests:
              cpu: 80m
              memory: 120Mi
      serviceAccountName: vm-operator
      terminationGracePeriodSeconds: 10
